/*	$NetBSD$	*/

/*-
 * Copyright (c) 2018 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */


/*
 * The micro ASan implementation for the userland (uASan) and kernel (kASan).
 * The uASan versions is suitable for inclusion into libc or used standalone
 * with ATF tests.
 *
 * This file due to long symbol names generated by a compiler during the
 * instrumentation process does not follow the KNF style with 80-column limit.
 */

#include <sys/cdefs.h>
#if defined(_KERNEL)
__KERNEL_RCSID(0, "$NetBSD$");
#else
__RCSID("$NetBSD$");
#endif


#if defined(__clang__) && (__clang_major__ - 0 >= 6)
#define ASAN_ABI_VERSION 8
#elif __GNUC_PREREQ__(7, 1) && !defined(__clang__)
#define ASAN_ABI_VERSION 8
#elif __GNUC_PREREQ__(6, 1) && !defined(__clang__)
#define ASAN_ABI_VERSION 6
#else
#error Unsupported compiler version
#endif

#define __asan_version_mismatch_check __CONCAT(__asan_version_mismatch_check,ASAN_ABI_VERSION)

int __asan_option_detect_stack_use_after_return = 1;

void __asan_handle_no_return(void);
void __asan_version_mismatch_check(void);
void __asan_init(void);
void __asan_before_dynamic_init(const char *module_name);
void __asan_register_globals(struct __asan_global *globals, size_t size);
void __asan_unregister_globals(struct __asan_global *globals, size_t size);

#define __ASAN_REPORT_PROTOTYPE(size)				\
void __asan_report_load##size(intptr_t addr);			\
void __asan_report_exp_load##size(intptr_t addr);		\
void __asan_report_load##size_noabort(intptr_t addr);		\
void __asan_report_store##size(intptr_t addr);			\
void __asan_report_exp_store##size(intptr_t addr);		\
void __asan_report_store##size_noabort(intptr_t addr);

__ASAN_REPORT_PROTOTYPE(1)
__ASAN_REPORT_PROTOTYPE(2)
__ASAN_REPORT_PROTOTYPE(4)
__ASAN_REPORT_PROTOTYPE(8)
__ASAN_REPORT_PROTOTYPE(16)

#define __ASAN_STACK_PROTOTYPE(class)				\
void __asan_stack_malloc_##size(intptr_t addr);

/*
GCC 6.x

     1  __asan_handle_no_return
     2  __asan_init
     3  __asan_option_detect_stack_use_after_return
     4  __asan_register_globals
     5  __asan_report_load1
     6  __asan_report_load2
     7  __asan_report_load4
     8  __asan_report_load8
     9  __asan_report_store1
    10  __asan_stack_malloc_1
    11  __asan_stack_malloc_2
    12  __asan_unregister_globals
    13  __asan_version_mismatch_check_v6

CLANG

     1  `__asan_handle_no_return'
     2  `__asan_init'
     3  `__asan_option_detect_stack_use_after_return'
     4  `__asan_register_globals'
     5  `__asan_report_load1'
     6  `__asan_report_load2'
     7  `__asan_report_load4'
     8  `__asan_report_load8'
     9  `__asan_report_store1'
    10  `__asan_report_store2'
    11  `__asan_report_store8'
    12  `__asan_stack_malloc_1'
    13  `__asan_stack_malloc_2'
    14  `__asan_unregister_globals'
    15  `__asan_version_mismatch_check_v8'

*/

static void
GetStackBaseSize(void **base, size_t *size)
{

	ASSERT(base);
	ASSERT(size);

	if (_lwp_self() == 1) {
		static void *mainbase = NULL;
		static size_t mainsize = 0;

		ASSERT(_dlauxinfo());

		if (mainbase == NULL && mainsize == 0) {
			const AuxInfo *aux;
			struct rlimit slimit;

			if (getrlimit(RLIMIT_STACK, &slimit) == -1)
				err(EXIT_FAILURE, "getrlimit");

			mainsize = slimit.rlim_cur;
			aux = _dlauxinfo();
			while ((aux++)->a_type != AT_NULL) {
				if (aux->a_type == AT_STACKBASE) {
#ifdef __MACHINE_STACK_GROWS_UP
					mainbase = aux->a_v;
#else
					mainbase = aux->a_v - mainsize;
#endif
					break;
				}
			}

			ASSERT(mainbase);
			ASSERT(mainsize > 0);
		}
		*base = mainbase;
		*size = mainsize;
	} else {
		int rv;
		pthread_t pt;
		pthread_attr_t attr;

		pt = pthread_self();
		if ((rv = pthread_getattr_np(pt, &attr)) != 0)
			err(EXIT_FAILURE, "pthread_getattr_np");
		if ((rv = pthread_attr_getstack(&attr, base, size)) != 0)
			err(EXIT_FAILURE, "pthread_attr_getstack");
		if ((rv = pthread_attr_destroy(&attr)) != 0)
			err(EXIT_FAILURE, "pthread_attr_destroy");
	}
}

static void
Poison(void *base, size_t size)
{
}

static void
Unpoison(void *base, size_t size)
{
}

void
__asan_handle_no_return(void)
{
	void *base;
	size_t size;

	GetStackBaseSize(&base, &size)

	Poison(base, size);
}

void
__asan_version_mismatch_check(void)
{
	/* A dummy function to check ASan ABI version */

	return;
}

void
__asan_init(void)
{
	/* Unimplemented activate ASan switch */

	return;
}

void
__asan_before_dynamic_init(const char *module_name)
{
	/* TODO ? */

	return;
}

void
__asan_register_globals(struct __asan_global *globals, size_t size)
{
}

void
__asan_unregister_globals(struct __asan_global *globals, size_t size)
{
}


#define __ASAN_REPORT(size)					\
void								\
__asan_report_load##size(intptr_t addr)				\
{								\
								\
	ReportOperating();					\
}								\
								\
void								\
__asan_report_exp_load##size(intptr_t addr)			\
{								\
								\
	ReportOperating();					\
}								\
								\
void								\
__asan_report_load##size_noabort(intptr_t addr)			\
{								\
								\
	ReportOperating();					\
}								\
								\
void								\
__asan_report_store##size(intptr_t addr)			\
{								\
								\
	ReportOperating();					\
}								\
								\
void								\
__asan_report_exp_store##size(intptr_t addr)			\
{								\
								\
	ReportOperating();					\
}								\
								\
void								\
__asan_report_store##size_noabort(intptr_t addr)		\
{								\
								\
	ReportOperating();					\
}

__ASAN_REPORT(1)
__ASAN_REPORT(2)
__ASAN_REPORT(4)
__ASAN_REPORT(8)
__ASAN_REPORT(16)
